version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    container_name: wooriFlask
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn wooriFlask.wsgi:application --bind 0.0.0.0:5000
    ports:
      - "5000:5000"